version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ management console port
    networks:
      - rabbitnet

  redis:
    image: redis:latest
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"  # Redis default port
    networks:
      - rabbitnet

  server:
    build: ./src/FasterAI/server
    container_name: server
    volumes:
      - ./src/FasterAI/server:/app/server
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
      - redis
    networks:
      - rabbitnet

  worker1:
    build: ./src/FasterAI/worker
    container_name: consumer1
    volumes:
      - ./src/FasterAI/worker:/app/worker
    depends_on:
      - rabbitmq
      - redis
      - server
    networks:
      - rabbitnet

  worker2:
    build: ./src/FasterAI/worker
    container_name: consumer2
    volumes:
      - ./src/FasterAI/worker:/app/worker
    depends_on:
      - rabbitmq
      - redis
      - server
    networks:
      - rabbitnet

networks:
  rabbitnet: